'use client';
import Link from 'next/link';
import { CalibrationPanel, CalibrationSummary } from '@/components/surveys/calibration';
import { Suspense, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { SURVEY_DIMENSIONS, type SurveyDimension } from '@geo/shared';
import { api, ApiError } from '@/lib/api';
import { EmptyState, PageHeader, Skeleton } from '@/components/ui';
import { SurveyError, SurveyStatus } from '@/components/surveys/common';
import { busySurvey, QUESTION_TYPES, type SurveyReport, type SurveyRow } from '@/components/surveys/types';
import { ResponseBrowser } from '@/components/surveys/response-browser';
import { downloadReport } from '@/components/surveys/export';

export default function SurveyReportsPage() { return <Suspense fallback={<Skeleton />}><Reports /></Suspense>; }
function Reports() {
  const sp = useSearchParams(), router = useRouter();
  const [dimension, setDimension] = useState<SurveyDimension | ''>('');
  const surveys = useQuery({ queryKey: ['surveys'], queryFn: () => api<SurveyRow[]>('/surveys'), refetchInterval: q => q.state.data?.some(s => busySurvey(s.status)) ? 3000 : false });
  const requested = Number(sp.get('surveyId'));
  const surveyId = Number.isSafeInteger(requested) && requested > 0 ? requested : surveys.data?.find(s => ['completed', 'partial'].includes(s.status))?.id ?? surveys.data?.[0]?.id;
  const selected = surveys.data?.find(s => s.id === surveyId);
  const report = useQuery({ queryKey: ['survey-report', surveyId, dimension], enabled: !!surveyId,
    queryFn: () => api<SurveyReport>(`/surveys/${surveyId}/report${dimension ? `?dimension=${dimension}` : ''}`),
    retry: false, refetchInterval: q => busySurvey(q.state.data?.status ?? selected?.status ?? '') ? 3000 : false });
  const data = report.data;
  return <div className="mx-auto max-w-6xl space-y-6"><PageHeader title="调研报告" desc="从分布看倾向，从原文发现顾虑。所有结果均来自合成样本。" actions={surveyId && <Link className="btn-ghost" href={`/surveys/${surveyId}?step=run`}>查看运行状态 →</Link>} />
    {surveys.isPending ? <Skeleton /> : surveys.error ? <SurveyError error={surveys.error} retry={() => void surveys.refetch()} /> : !surveys.data?.length ? <EmptyState title="还没有调研报告" text="创建一份调研，确认问卷与人群，完成作答后即可在这里查看结果。" /> : <>
      <div className="card flex flex-wrap items-end gap-4 p-4"><label className="min-w-0 flex-1 text-xs font-medium text-slate-500">选择调研<select aria-label="选择调研" className="input mt-2" value={surveyId ?? ''} onChange={e => router.replace(`/surveys/reports?surveyId=${e.target.value}`)}>{!selected && <option value={surveyId}>指定调研 #{surveyId}</option>}{surveys.data.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label className="text-xs font-medium text-slate-500">分组对比<select aria-label="分组对比" className="input mt-2 w-auto" value={dimension} onChange={e => setDimension(e.target.value as SurveyDimension | '')}><option value="">全部样本</option>{Object.entries(SURVEY_DIMENSIONS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
      {report.isPending ? <Skeleton /> : report.error && !(report.error instanceof ApiError && report.error.code === 404) ? <SurveyError error={report.error} retry={() => void report.refetch()} /> : !data ? <EmptyState title={busySurvey(selected?.status ?? '') ? '正在等待有效回答' : '这份调研还没有有效回答'} text={busySurvey(selected?.status ?? '') ? '本页会自动更新，第一份有效回答保存后即可查看分布。' : '在调研详情中确认人群并开始作答，已有失败任务可补跑。'} /> : <>
        <section className="card overflow-hidden"><div className="bg-brand-50 p-6 sm:p-8"><div className="mb-3 flex flex-wrap items-center gap-3"><span className="text-xs font-semibold tracking-widest text-brand-700">合成样本 · 探索性调研</span><SurveyStatus status={data.status} /></div><h2 className="break-words text-2xl font-semibold text-slate-900">{data.title}</h2><p className="mt-3 break-words text-sm leading-7 text-slate-600">{data.objective}</p><dl className="mt-6 grid grid-cols-3 gap-4"><div><dt className="text-xs text-slate-500">有效样本</dt><dd className="mt-1 text-3xl font-semibold tabular-nums">{data.sampleSize}<span className="ml-1 text-sm font-normal text-slate-400">/ {data.progress.total}</span></dd></div><div><dt className="text-xs text-slate-500">样本完成率</dt><dd className="mt-1 text-3xl font-semibold tabular-nums">{data.progress.total ? Math.round(data.sampleSize / data.progress.total * 100) : 0}<span className="text-base">%</span></dd></div><div><dt className="text-xs text-slate-500">问卷长度</dt><dd className="mt-1 text-3xl font-semibold">{data.questions.length}<span className="ml-1 text-sm font-normal text-slate-400">题</span></dd></div></dl></div><div className="space-y-3 p-5"><p className="text-sm leading-6 text-slate-700">{data.disclaimer}</p><ul className="list-disc space-y-1 pl-4 text-xs leading-6 text-slate-500">{data.warnings.map(w => <li key={w}>{w}</li>)}</ul><div className="flex flex-wrap gap-2 pt-2"><button className="btn-ghost" onClick={() => downloadReport(data, 'csv')}>导出 CSV</button><button className="btn-ghost" onClick={() => downloadReport(data, 'json')}>导出 JSON</button><span className="self-center text-xs text-slate-400">导出包含当前分组、样本量与合成声明</span></div></div></section>
        {data.calibration && <CalibrationSummary record={data.calibration} />}<div className="space-y-5">{data.questions.map((q, index) => <QuestionResult key={`${surveyId}-${q.question.id}`} result={q} index={index} dimension={dimension} />)}</div>
        <details className="card p-5"><summary className="cursor-pointer text-sm font-semibold">逐条查看每份答卷<span className="ml-2 text-xs font-normal text-slate-400">读原文,不只看分布</span></summary><div className="mt-4">{data.sampleSize > 0 && <ResponseBrowser surveyId={surveyId!} questions={data.questions.map(q => q.question)} />}</div></details>
        <details className="card p-5"><summary className="cursor-pointer text-sm font-semibold">样本来源与配额记录</summary><p className="mt-3 text-xs leading-6 text-slate-500">人物来源：{data.pool.sourceMode === 'persona_hub' ? 'Persona Hub' : data.pool.sourceMode === 'hybrid' ? 'Persona Hub 与配额生成混合' : '配额生成'}；Persona Hub {data.pool.sourceStats.personaHub ?? 0} 人，生成 {data.pool.sourceStats.generated ?? data.pool.size} 人。{data.calibration ? '已应用真人基准权重，详见校准记录。' : '未应用真人基准权重。'} AI 建议与最终选择分别保留。</p><div className="mt-4 grid gap-5 sm:grid-cols-2">{[{ title: 'AI 初始建议', segments: data.suggestedSegments }, { title: '实际采用配额', segments: data.pool?.spec.segments ?? [] }].map(group => <div key={group.title}><h3 className="mb-2 text-sm font-medium">{group.title}</h3>{!group.segments.length ? <p className="text-xs text-slate-400">未使用 AI 建议</p> : <ul className="space-y-2 text-xs leading-6 text-slate-600">{group.segments.map((s, i) => <li key={i} className="rounded-lg bg-slate-50 p-3">{[s.gender, s.ageBand, s.cityTier, s.incomeBand, s.occupationGroup].join(' · ')} <strong>× {s.count}</strong></li>)}</ul>}</div>)}</div></details><div id="calibration" className="scroll-mt-20"><CalibrationPanel key={surveyId} surveyId={surveyId!} questions={data.questions.map(q => q.question)} enabled={!busySurvey(data.status) && data.sampleSize >= 5} /></div>
      </>}
    </>}
  </div>;
}
function QuestionResult({ result: q, index, dimension }: { result: SurveyReport['questions'][number]; index: number; dimension: string }) {
  const [search, setSearch] = useState(''), [expanded, setExpanded] = useState(false);
  const matching = q.responses.filter(r => r.includes(search));
  return <article className="card p-5 sm:p-7"><div className="mb-3 flex items-center gap-2 text-xs text-slate-400"><span className="font-semibold text-brand-700">Q{String(index + 1).padStart(2, '0')}</span><span>{QUESTION_TYPES[q.question.type]}</span><span className="ml-auto">有效 N = {q.sampleSize}</span></div><h3 className="break-words text-base font-semibold leading-7">{q.question.text}</h3>
    {q.mean !== null && <p className="mt-4 text-sm text-slate-500">加权均值 <strong className="ml-2 text-2xl font-semibold text-brand-700">{q.mean.toFixed(2)}</strong> / 10</p>}
    {q.question.type === 'open' ? <div className="mt-4"><label className="text-xs text-slate-500">检索原始回答<input className="input mt-2" placeholder="输入关键词，如价格、售后" value={search} onChange={e => setSearch(e.target.value)} /></label><p className="my-3 text-xs text-slate-400">共 {q.sampleSize} 份回答，当前提供前 {q.responses.length} 份原文，匹配 {matching.length} 份。原文为 AI 合成，未作主题归纳。</p><div className="space-y-2">{matching.slice(0, expanded ? undefined : 5).map((r, i) => <blockquote key={i} className="break-words rounded-lg border-l-2 border-brand-200 bg-slate-50 p-4 text-sm leading-7 text-slate-600">{r}</blockquote>)}{!matching.length && <p className="py-5 text-center text-sm text-slate-400">没有匹配的回答</p>}</div>{matching.length > 5 && <button className="btn-ghost mt-3" onClick={() => setExpanded(!expanded)}>{expanded ? '收起回答' : `展开全部 ${matching.length} 份`}</button>}</div> : q.question.type === 'scale' ? <div className="mt-5"><div className="grid h-36 grid-cols-10 items-end gap-1.5 sm:gap-3">{q.distribution.map(d => <div key={d.value} className="flex h-full flex-col items-center gap-2" title={`${d.value} 分：${d.count} 人，${(d.share * 100).toFixed(1)}%`} aria-label={`${d.value} 分，${d.count} 人，${(d.share * 100).toFixed(1)}%`}><span className="text-[10px] tabular-nums text-slate-400">{Math.round(d.share * 100)}%</span><div className="flex w-full flex-1 items-end overflow-hidden rounded-t-md bg-slate-50"><div className="w-full rounded-t-md bg-brand-500" style={{ height: `${Math.min(100, d.share * 100)}%` }} /></div><span className="text-xs tabular-nums text-slate-500">{d.value}</span></div>)}</div><p className="mt-3 text-xs text-slate-400">1–10 分分布 · 百分比按作答人数加权</p></div> : <div className="mt-5 space-y-4">{q.distribution.map(d => <div key={d.value}><div className="mb-1.5 flex items-baseline justify-between gap-4 text-sm"><span className="min-w-0 break-words text-slate-600">{d.value}</span><span className="shrink-0 tabular-nums"><strong className="font-medium text-slate-800">{(d.share * 100).toFixed(1)}%</strong><span className="ml-2 text-xs text-slate-400">{d.count} 人</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${Math.max(0, Math.min(100, d.share * 100))}%` }} /></div></div>)}{q.question.type === 'multi' && <p className="text-xs leading-6 text-slate-400">多选题按作答人数计算每个选项的选择率，合计可能超过 100%。</p>}</div>}
    {dimension && q.question.type !== 'open' && <details className="mt-5 border-t border-slate-100 pt-4" open><summary className="cursor-pointer text-sm font-medium">分组对比 <span className="font-normal text-slate-400">· 小样本仅作探索</span></summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-100 text-slate-400"><th className="min-w-24 py-3 pr-4 font-normal">分组 / 有效 N</th>{q.distribution.map(d => <th key={d.value} className="min-w-20 px-3 py-3 font-normal">{d.value}</th>)}</tr></thead><tbody>{q.groups.map(g => <tr key={g.label} className="border-b border-slate-50"><th className="py-3 pr-4 font-medium text-slate-600">{g.label}<span className="ml-2 text-slate-400">{g.sampleSize}</span></th>{g.distribution.map(d => <td key={d.value} className="px-3 py-3 tabular-nums text-slate-600">{(d.share * 100).toFixed(1)}%</td>)}</tr>)}</tbody></table></div></details>}
  </article>;
}
