'use client';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, isAdmin } from '@/lib/api';
import { Badge, Skeleton } from '@/components/ui';
import { SurveyError } from './common';
interface LibraryData {
  rows: Array<{ id: number; description: string; profile: Record<string, unknown> | null; status: string; sourceUrl: string; license: string; lastError: string | null }>;
  counts: { total: number; ready: number; pending: number; failed: number };
  jobs: Array<{ id: number; status: string; requestedCount: number; processed: number; imported: number; lastError: string | null }>;
  hasMore: boolean; allowed: boolean; license: string; sourceRevision: string; sourceUrl: string;
}
const STATUS: Record<string,string> = { imported: '已导入', queued: '等待增强', enriching: '增强中', ready: '可抽样', failed: '需重试', completed: '已完成', running: '导入中' };
export function PersonaLibraryPanel() {
  const cache = useQueryClient(); const [q, setQ] = useState(''), [offset,setOffset] = useState(0), [count,setCount] = useState(100), [batch,setBatch] = useState(20);
  const data = useQuery({ queryKey: ['persona-library', q, offset], queryFn: () => api<LibraryData>(`/persona-library?q=${encodeURIComponent(q)}&offset=${offset}`), refetchInterval: query => query.state.data?.counts.pending || query.state.data?.jobs.some(j => ['queued','running'].includes(j.status)) ? 3000 : false });
  const action = useMutation({ mutationFn: ({ path, count }: { path: string; count: number }) => api(`/persona-library/${path}`, { method: 'POST', json: { count } }), onSuccess: () => cache.invalidateQueries({ queryKey: ['persona-library'] }) });
  if (data.isPending) return <Skeleton />;
  if (data.error || !data.data) return <SurveyError error={data.error ?? new Error('人群库读取失败')} retry={() => void data.refetch()} />;
  const library = data.data;
  return <div className="space-y-5"><section className="card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Persona Hub 共享档案</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-500">保留原始描述，由模型提取职业与性格。缺失的人口属性保持未知，问卷抽样时再使用你确认的配额赋值。</p></div><a href="https://github.com/tencent-ailab/persona-hub" target="_blank" rel="noreferrer" className="text-xs text-brand-700 underline">查看原始数据与许可 ↗</a></div><dl className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">{[['已入库',library.counts.total],['可抽样',library.counts.ready],['等待增强',library.counts.pending],['需重试',library.counts.failed]].map(([label,value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-2xl font-semibold tabular-nums">{value}</dd></div>)}</dl><p className="mt-4 text-xs leading-6 text-slate-500">数据许可：{library.license}（非商业使用）；当前{library.allowed ? '环境可用于研究' : '未取得商业授权，导入与抽样停用'}。上游版本 {library.sourceRevision.slice(0,12)}。增强是模型提取结果，使用前应抽检原文。</p>
    {isAdmin() && <div className="mt-5 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2"><div><label className="text-xs text-slate-500">导入前 N 条（自动去重）<input aria-label="Persona Hub 导入数量" className="input mt-2" type="number" min={1} max={200000} value={count} onChange={e=>setCount(Number(e.target.value))} /></label><button className="btn-soft mt-3" disabled={!library.allowed || action.isPending || count < 1 || count > 200000 || !Number.isInteger(count)} onClick={()=>action.mutate({path:'imports',count})}>导入 Persona Hub</button></div><div><label className="text-xs text-slate-500">本批增强数量（每条一次模型调用）<input aria-label="人物增强数量" className="input mt-2" type="number" min={1} max={500} value={batch} onChange={e=>setBatch(Number(e.target.value))} /></label><button className="btn-primary mt-3" disabled={!library.allowed || action.isPending || batch < 1 || batch > 500 || !Number.isInteger(batch) || !library.counts.total} onClick={()=>action.mutate({path:'enrich',count:batch})}>结构化增强 / 重试</button></div></div>}
    {!isAdmin() && !library.counts.ready && <p className="mt-4 text-sm text-slate-500">请联系平台管理员导入并增强人物，之后即可在问卷中选用。</p>}{action.error && <div className="mt-4"><SurveyError error={action.error} /></div>}
    {library.jobs.length > 0 && <details className="mt-5"><summary className="cursor-pointer text-xs text-slate-500">最近导入记录</summary><ul className="mt-3 space-y-2 text-xs text-slate-600">{library.jobs.map(j=><li key={j.id}>#{j.id} {STATUS[j.status]??j.status} · 读取 {j.processed}/{j.requestedCount} · 新增 {j.imported}{j.lastError ? ` · ${j.lastError}` : ''}</li>)}</ul></details>}</section>
    <label className="block text-xs text-slate-500">检索人物原文<input className="input mt-2" aria-label="检索人物原文" placeholder="例如 engineer、teacher" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}} /></label>
    <p className="rounded-xl bg-slate-50 px-4 py-3 text-xs leading-6 text-slate-600">这里的档案是<b>源材料</b>：一句原始描述 + 增强出的职业/性格。它们本身不是调研问卷里的成品人物——创建调研并在「人物来源」选择 Persona Hub 后，源档案会与你的配额结合，生成带姓名、城市、家庭、消费观的成品人物（可在调研向导的「逐条查看人群名单」里审阅）。</p>
    {!library.rows.length ? <p className="card p-8 text-center text-sm text-slate-500">{q ? '没有匹配的档案' : '尚未导入人物档案'}</p> : <div className="grid gap-4 lg:grid-cols-2">{library.rows.map(row=><article key={row.id} className="card p-5"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">Persona #{row.id}</span><Badge label={STATUS[row.status]??row.status} tone={row.status==='ready'?'good':row.status==='failed'?'warn':'slate'} /></div><p className="mt-3 break-words text-sm leading-7 text-slate-700">{row.description}</p>{row.status==='imported' && <p className="mt-3 text-xs leading-6 text-slate-400">源描述尚未增强：增强后会提取职业与性格等结构化字段；原文没有的人口属性（年龄/城市/收入）保持未知，不猜测。</p>}{row.profile && <div className="mt-4 rounded-lg bg-brand-50 p-3 text-xs leading-6 text-slate-600"><p>职业：{String(row.profile.occupation??'未知')} · {String(row.profile.occupationGroup??'未知')}</p><p>性格：{Array.isArray(row.profile.traits)?row.profile.traits.join('、'):'未知'}</p><p>年龄：{String(row.profile.ageBand??'未知')} · 城市：{String(row.profile.cityTier??'未知')} · 收入：{String(row.profile.incomeBand??'未知')}</p></div>}{row.lastError && <p className="mt-3 text-xs text-warn-600">{row.lastError}</p>}</article>)}</div>}
    <div className="flex items-center justify-between"><button className="btn-ghost" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-30))}>上一页</button><span className="text-xs text-slate-400">第 {Math.floor(offset/30)+1} 页</span><button className="btn-ghost" disabled={!library.hasMore} onClick={()=>setOffset(offset+30)}>下一页</button></div>
  </div>;
}
