import { chromium } from 'playwright-core';
const API = 'http://localhost:3000';
const r1 = await fetch(`${API}/auth/sms/code`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '13800001234' }) }).then(r => r.json());
const r2 = await fetch(`${API}/auth/sms/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '13800001234', code: r1.devCode }) }).then(r => r.json());
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 } });
const page = await ctx.newPage();
await page.addInitScript(([t]) => { localStorage.setItem('geo.accessToken', t); localStorage.setItem('geo.brandId', '1'); }, [r2.accessToken]);
const errors = [];
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:3001/dashboard', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
const svgs = await page.locator('.card svg').count();
const sparkText = await page.evaluate(() => document.body.innerHTML.includes('Sparkline'));
console.log('card svg count:', svgs, '| has spark str:', sparkText);
console.log('page errors:', errors.slice(0, 3));
await browser.close();
