import { chromium } from 'playwright-core';
const API = 'http://localhost:3000';
const r1 = await fetch(`${API}/auth/sms/code`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '13800001234' }) }).then(r => r.json());
const r2 = await fetch(`${API}/auth/sms/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '13800001234', code: r1.devCode }) }).then(r => r.json());
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.addInitScript(([t]) => { localStorage.setItem('geo.accessToken', t); localStorage.setItem('geo.brandId', '1'); }, [r2.accessToken]);
await page.goto('http://localhost:3001/dashboard', { waitUntil: 'networkidle' });
await page.waitForTimeout(1400);
console.log('card svg count:', await page.locator('.card svg').count());
await page.locator('.grid.grid-cols-2').first().screenshot({ path: '/tmp/geo-shots/zoom-cards.png' });
await browser.close();
